- name: Check kube-controller-manager status
  shell: "systemctl status kube-controller-manager |grep 'Active:' | cut -d '(' -f2|cut -d ')' -f1"
  register: kube_cm_status


- name: Echo kube-controller-manager status
  debug:
    msg: "Current controller-manager status: {{ kube_cm_status.stdout }}"

- name: Check kube-controller-manager list port
  shell: "netstat -lnpt | grep 1025[28]"
  register: cm_listen_port

- name: Echo listen port
  debug:
    msg: "{{ cm_listen_port.stdout }}"

- name: Check controller-manager metrics
  shell: "curl -s --cacert {{ K8S_SSL_DIR }}/ca.pem --cert {{ K8S_SSL_DIR }}/admin.pem --key {{ K8S_SSL_DIR }}/admin-key.pem https://{{ ansible_host }}:10258/metrics |head"
  register: cm_metrics_status

- name: Echo controller-manager metrics
  debug:
    msg: "{{ cm_metrics_status.stdout_lines|list }}"

- name: Check controller-manager Leader
  shell: "{{ KUBECTL_CMD }} get endpoints kube-controller-manager --namespace=kube-system  -o yaml"
  register: leader_status

- name: Echo controller-manager Leader
  debug:
    msg: "{{ leader_status.stdout_lines|list  }}"
