- name: Rollback kube-controller-manager
  block: 
    - name: Stop kube-controller-manager service
      include_role:
        name: common
        tasks_from: stop-controller-manager
    - name: Copy kube-controller-manager exe
      copy:
        remote_src: True
        src: "{{ K8S_DIR }}/bin/kube-controller-manager.bk"
        dest: "{{ K8S_DIR }}/bin/kube-controller-manager"
    
    - name: Copy kube-controller-manager system unit
      copy:
        remote_src: True
        src: "{{ SYSTEMD_CFG_DIR }}/kube-controller-manager.service.bk"
        dest: "{{ SYSTEMD_CFG_DIR }}/kube-controller-manager.service"
    - name: Start kube-controller-manager service
      include_role:
        name: common
        tasks_from: start-controller-manager
  # when: (op is defined) and (op == "rollback")

- name: Check kube-controller-manager
  import_tasks: check.yml