- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Stop and disable etcd process
  shell: "systemctl stop kube-etcd; 
          systemctl disable kube-etcd"
  register: shell_result
  failed_when: not (shell_result.rc == 0 or "No such file or directory" in shell_result.stderr)

- name: Delete etcd data dir
  shell: "rm -rf {{ ETCD_DIR }}/lib/etcd"

- name: Delete systemd unit files
  shell: "rm -rf /etc/systemd/system/kube-etcd.service*"

- name: Delete etcd backup file
  shell: "rm -rf {{ ETCD_BACKUP_DIR }}"
