- name: Check kube-apiserver
  import_role:
    name: common
    tasks_from: check-apiserver
- name: Check whether container restart
  import_role:
    name: common
    tasks_from: check-container
  vars:
    component: apiserver