- name: Rollback kube-apiserver
  block:
    - name: Stop kube-apiserver service
      include_role:
        name: common
        tasks_from: stop-apiserver

    - name: Copy apiserver exe
      copy:
        remote_src: True
        src: "{{ K8S_DIR }}/bin/kube-apiserver.bk"
        dest: "{{ K8S_DIR }}/bin/kube-apiserver"

    - name: Copy apiserver system unit
      copy:
        remote_src: True
        src: "{{ SYSTEMD_CFG_DIR }}/kube-apiserver.service.bk"
        dest: "{{ SYSTEMD_CFG_DIR }}/kube-apiserver.service"
    
    - name: Start kube-apiserver service
      include_role:
        name: common
        tasks_from: start-apiserver
  # when: (op is defined) and (op == "rollback")
- name: Check kube-apiserver
  import_tasks: check.yml