- name: Rollback kubelet
  block:
    - name: Stop kubelet service
      include_role:
        name: common
        tasks_from: stop-kubelet
    
    - name: Copy kubelet exe
      copy:
        remote_src: True
        src: "{{ K8S_DIR }}/bin/kubelet.bk"
        dest: "{{ K8S_DIR }}/bin/kubelet"

    - name: Copy kubelet system unit
      copy:
        remote_src: True
        src: "{{ SYSTEMD_CFG_DIR }}/kubelet.service.bk"
        dest: "{{ SYSTEMD_CFG_DIR }}/kubelet.service"

    - name: Start kubelet service
      include_role:
        name: common
        tasks_from: start-kubelet
  # when: (op is defined) and (op == "rollback")
- name: Check kubelet
  import_tasks: check.yml