- name: Upgrade kubelet
  block:
    - name: Mkdir kubelet dir
      file:
        path: "{{ K8S_DIR }}/{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - lib/kubelet
        - kubelet
    - name: Get old kubelet system unit path
      shell: "systemctl status kubelet| grep Loaded: | cut -d '(' -f2|cut -d ';' -f1"
      register: old_config_path
    - name: debug
      debug: var=old_config_path.stdout

    - name: Copy kubelet conf
      template:
        src: "roles/kube-node/templates/{{ item }}.j2"
        dest: "{{ K8S_DIR }}/etc/kubernetes/{{ item }}"
      with_items:
        - "resolv.conf"
        - "kubelet-config.yaml"

    - name: Copy kubelet system unit
      template:
        src: roles/kube-node/templates/{{ item }}.j2
        dest: "{{ SYSTEMD_CFG_DIR }}/{{ item }}.16"
      with_items:
        - "kubelet.service"

    - name: Backup kubelet old system unit
      copy:
        remote_src: True
        src: "{{ item }}"
        dest: "{{ SYSTEMD_CFG_DIR }}/kubelet.service"
        mode: 0755
      with_items:
        - "{{ old_config_path.stdout }}"
    - name: Stop kubelet service
      include_role:
        name: common
        tasks_from: stop-kubelet

    - name: Move backup.sh
      copy:
        src: "roles/common/files/backup.sh"
        dest: "{{ K8S_DIR }}/bin/"
        mode: 0755

    - name: Execute whether backup system unit
      shell: "{{ K8S_DIR }}/bin/backup.sh {{ SYSTEMD_CFG_DIR }}/kubelet.service.16 {{ SYSTEMD_CFG_DIR }}/kubelet.service"


    - name: Execute whether backup kubelet
      shell: "{{ K8S_DIR }}/bin/backup.sh {{ K8S_DIR }}/bin/kubelet.16 {{ K8S_DIR }}/bin/kubelet"

    - name: Copy pause image tar 
      copy:
        src: "roles/kube-node/files/pause-amd64.tar"
        dest: "/opt/k8s/work/"

    - name: Docker load pause-amd64.tar
      shell: "docker load -i /opt/k8s/work/pause-amd64.tar"

    - name: Start kubelet service
      include_role:
        name: common
        tasks_from: start-kubelet

  # when: (op is not defined) or (op == "upgrade")

- name: Check kubelet
  import_tasks: check.yml