- name: Roll back kube-proxy
  block:
    - name: Stop kube-proxy service
      include_role:
        name: common
        tasks_from: stop-kube-proxy
    - name: Clean rules
      import_tasks: clean-rules.yml

    - name: Copy kube-proxy exe
      copy:
        remote_src: True
        src: "{{ K8S_DIR }}/bin/kube-proxy.bk"
        dest: "{{ K8S_DIR }}/bin/kube-proxy"
    
    - name: Copy kube-proxy config | kube-proxy-config.yaml
      copy:
        remote_src: True
        src: "{{ K8S_DIR }}/etc/kubernetes/{{ item }}.bk"
        dest: "{{ K8S_DIR }}/etc/kubernetes/{{ item }}"
      ignore_errors: yes
      with_items:
        - kube-proxy-config.yaml

    - name: Copy kube-proxy system unit
      copy:
        remote_src: True
        src: "{{ SYSTEMD_CFG_DIR }}/kube-proxy.service.bk"
        dest: "{{ SYSTEMD_CFG_DIR }}/kube-proxy.service"

    - name: Start kube-proxy service
      include_role:
        name: common
        tasks_from: start-kube-proxy

  # when: (op is defined) and (op == "rollback")
- name: Check kube-proxy
  import_tasks: check.yml