
- name: Get iptables version
  shell: "iptables --version"
  register: iptables_version

- name: Echo ipables version
  debug: var=iptables_version.stdout

- name: Upgrade iptables
  block:
    - name: Copy iptables files
      copy:
        src: "roles/common/files/iptables-1.6.2"
        dest: "{{ K8S_TMP_DIR }}/work"
        directory_mode: yes
    - name: Install deps for iptables-1.6.2
      shell: "rpm -ivh {{ K8S_TMP_DIR }}/work/iptables-1.6.2/*.rpm --nodeps --force"
      # with_items:
      #   - perl-version-0.99.07-6.el7.x86_64.rpm
      #   - m4-1.4.16-10.el7.x86_64.rpm
      #   - perl-Data-Dumper-2.145-3.el7.x86_64.rpm
      #   - autoconf-2.69-11.el7.noarch.rpm
      #   - perl-Test-Harness-3.28-3.el7.noarch.rpm
      #   - mpfr-3.1.1-4.el7.x86_64.rpm
      #   - libmpc-1.0.1-3.el7.x86_64.rpm
      #   - cpp-4.8.5-39.el7.x86_64.rpm
      #   - kernel-headers-3.10.0-1127.el7.x86_64.rpm
      #   - glibc-common-2.17-307.el7.1.x86_64.rpm
      #   - glibc-headers-2.17-307.el7.1.x86_64.rpm
      #   - glibc-devel-2.17-307.el7.1.x86_64.rpm
      #   - glibc-2.17-307.el7.1.x86_64.rpm
      #   - libgcc-4.8.5-39.el7.x86_64.rpm
      #   - libgomp-4.8.5-39.el7.x86_64.rpm
      #   - gcc-4.8.5-39.el7.x86_64.rpm
      #   - automake-1.13.4-3.el7.noarch.rpm
      #   - libtool-2.4.2-22.el7_3.x86_64.rpm
      #   - libmnl-devel-1.0.3-7.el7.x86_64.rpm
      #   - libnftnl-1.0.8-3.el7.x86_64.rpm
      #   - libnftnl-devel-1.0.8-3.el7.x86_64.rpm
      #   - bison-3.0.4-2.el7.x86_64.rpm
      #   - flex-2.5.37-6.el7.x86_64.rpm
      #   - perl-Thread-Queue-3.02-2.el7.noarch.rpm
      # ignore_errors: true
    - name: Unarchive iptables file
      unarchive:
        src: "{{ K8S_TMP_DIR }}/work/iptables-1.6.2/iptables-1.6.2.tar.gz"
        dest: "{{ K8S_TMP_DIR }}/work/iptables-1.6.2"
        remote_src: yes
    - name: Install iptables 1.6.2
      shell: "sh {{ K8S_TMP_DIR }}/work/iptables-1.6.2/install.sh"
  when: iptables_version.stdout.find("1.6.2") == -1
