- name: Get ipvsadm version
  shell: "ipvsadm --version"
  register: ipvsadm_version
  ignore_errors: true

- name: Echo ipables version
  debug: var=ipvsadm_version.stdout

- name: Upgrade ipvsadm
  block:
    - name: Copy ipvsadm files
      copy:
        src: "roles/common/files/ipvsadm-1.27"
        dest: "{{ K8S_TMP_DIR }}/work"
        directory_mode: yes
    - name: Intall ipvsadm
      shell: "rpm -ivh {{ K8S_TMP_DIR }}/work/ipvsadm-1.27/*.rpm --nodeps --force"
  when: ipvsadm_version.rc != 0